# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:tAAYeDOB39xeQY3oozlPXJPVGRZeFH+JhmrB37xdjmZd9lZ15b4ggQ==,iv:3Np1eZbEqydwetqYkOtazLa7Og5hYXaK32SGL91yGyA=,tag:Oh0BRxdwCeLdBSedETX7/A==,type:str]
sops:
  age:
    - recipient: age1s0t937a3fa0m6wrhuyk5gasujqw584l382zjpc75885f2set9uksfs94jf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDMDhwT3Z3K2VJU1FGSGkx
        dHZOTEZMd0ZrdU1oVHMvNkVmTGZsWmlGQTFjCkxHckllb1h5RStGZWtKNS9YRE8y
        MEZhOWZWMHU5ZHBMRmV4ekMybTJYU0UKLS0tIGs3SE9DbHAxaTM3b3lQV3pBTWE4
        SE5kSGx1MHpQRDMyazE0aTY3T3J4cEEKbu+RKOyXKwxMwSw3VUQHbbmIXpQpNltt
        8Cugdw9eWvfhxWyDmoG11Hiuwk1Ko8b4QIiYjw1Zr97JA/aRn09P3g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-31T14:30:45Z"
  mac: ENC[AES256_GCM,data:SzKOJbWV9SXdqBZSsBKPJz2/ZsWegRhECUSz2CG1mSS7ZNwl/CofTi3FklXzGaDDw4xp5VPEwHhU7u3ZEvoPxU6uVcDDGsAsPr60hbEQD34YLtj1DpA5kYfsI9t9H6DmceXBQzayckAMHW9BZSikpwMpHFoHFGKkPeczRY3RtFg=,iv:shokpYvuY7hYGhqlCmXw4Ea3dnC9phdWDOcXdFJQYAk=,tag:ojfcI4aHkdLowRZNMNEMMg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
