---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "${APP}-volsync-minio"
spec:
  dataFrom:
    - extract:
        key: volsync
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: "${APP}-volsync-minio-secret"
    template:
      data:
        AWS_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
        RESTIC_REPOSITORY: "{{ .RESTIC_REPOSITORY }}/${APP}"
      engineVersion: v2
