---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: "${APP}-dst"
spec:
  restic:
    accessModes: ["${VOLSYNC_ACCESSMODES:-ReadWriteOnce}"]
    cacheAccessModes: ["${VOLSYNC_CACHE_ACCESSMODES:-ReadWriteOnce}"]
    cacheCapacity: "${VOLSYNC_CACHE_CAPACITY:-5Gi}"
    capacity: "${VOLSYNC_CAPACITY:-5Gi}"
    copyMethod: Snapshot
    moverSecurityContext:
      fsGroup: ${VOLSYNC_PGID:-3000}
      runAsGroup: ${VOLSYNC_PGID:-3000}
      runAsUser: ${VOLSYNC_PUID:-3000}
    repository: "${APP}-volsync-minio-secret"
    storageClassName: "${VOLSYNC_STORAGECLASS:-longhorn}"
    volumeSnapshotClassName: "${VOLSYNC_SNAPSHOTCLASS:-longhorn}"
  trigger:
    manual: restore-once
