---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: "${APP}-minio"
spec:
  restic:
    accessModes: ["${VOLSYNC_SNAP_ACCESSMODES:-ReadWriteOnce}"]
    cacheAccessModes: ["${VOLSYNC_CACHE_ACCESSMODES:-ReadWriteOnce}"]
    cacheCapacity: "${VOLSYNC_CACHE_CAPACITY:-5Gi}"
    copyMethod: "${VOLSYNC_COPYMETHOD:-Snapshot}"
    moverSecurityContext:
      fsGroup: ${VOLSYNC_PGID:-3000}
      runAsGroup: ${VOLSYNC_PGID:-3000}
      runAsUser: ${VOLSYNC_PUID:-3000}
    pruneIntervalDays: 7
    repository: "${APP}-volsync-minio-secret"
    retain:
      daily: 7
      hourly: 24
      weekly: 5
    storageClassName: "${VOLSYNC_STORAGECLASS:-longhorn}"
    volumeSnapshotClassName: "${VOLSYNC_SNAPSHOTCLASS:-longhorn}"
  sourcePVC: "${APP}"
  trigger:
    schedule: "0 * * * *"
