---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationdestination_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: "${APP}-dst"
spec:
  restic:
    repository: "${APP}-volsync-minio-secret"
    copyMethod: Snapshot
    accessModes: ["${VOLSYNC_ACCESSMODES:-ReadWriteOnce}"]
    cacheAccessModes: ["${VOLSYNC_CACHE_ACCESSMODES:-ReadWriteOnce}"]
    cacheCapacity: "${VOLSYNC_CACHE_CAPACITY:-5Gi}"
    capacity: "${VOLSYNC_CAPACITY:-5Gi}"
    moverSecurityContext:
      fsGroup: ${VOLSYNC_PGID:-568}
      runAsGroup: ${VOLSYNC_PGID:-568}
      runAsUser: ${VOLSYNC_PUID:-568}
    storageClassName: "${VOLSYNC_STORAGECLASS:-longhorn}"
    volumeSnapshotClassName: "${VOLSYNC_SNAPSHOTCLASS:-longhorn}"
    cacheStorageClassName: "${VOLSYNC_CACHE_STORAGECLASS:-longhorn-cache}"
    enableFileDeletion: true
    cleanupCachePVC: true
    cleanupTempPVC: false
  trigger:
    manual: restore-once
