---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn-release
spec:
  chart:
    spec:
      chart: longhorn
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: longhorn-repo
      version: v1.9.0
  interval: 1m0s
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      strategy: rollback
  values:
    monitoring:
      enabled: true
    persistence:
      # Change to 3 later
      defaultClassReplicaCount: 2
    defaultSettings:
      defaultDataPath: /var/lib/longhorn
      defaultLonghornStaticStorageClass: longhorn
      nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
      storageReservedPercentageForDefaultDisk: 10
      createDefaultDiskLabeledNodes: true
      defaultReplicaCount: 2 # Change to 3 later
      orphanAutoDeletion: true
