apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:qFgKMxH7NrXZ,iv:rFJUO5IKJr/wWBYOPB9rdMdNP1IAPHJqy4upMFWcVR8=,tag:+VDo0O3QfW1uKSPiPDYOBQ==,type:str]
sops:
  age:
    - recipient: age1s0t937a3fa0m6wrhuyk5gasujqw584l382zjpc75885f2set9uksfs94jf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6ZGdqN2hwMDg4b2ZPTkNt
        d0VEOGdVYTVyL1lnNWp4TVAyK3VTa0xqaDM4Cnp5VkI4WlByWnFSNEg0VmVrekgy
        ZUVsNG42Sk1NTUN4L0I3S1VXYmVzbEUKLS0tIGRoRXZZS3BGKzZDbkJ2MXIwK3k1
        WStKMmRia2VoN010TlFRd3p6STNYR1UKff5fxRfUOIPCMgiVsYJ1Hc6GkaJVZbtQ
        HmIdROdmW92DGZHaisrBCYrkpjsXZ8K1tIKXrZ8RSF2OsyNgYcnB+g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-31T14:08:23Z"
  mac: ENC[AES256_GCM,data:gRUE4MdRKL2/qmAROAj2oe4EYGaPeksCawTjj1DQxzWkTLgzE2iabU8n76uOGiKVNH66kLlpyoqM6TItkGaqGxWc5dqT+eciKhWe8+kU5kmkrK9P8v2nDjkRUB2sR3S+F1O5dysM7AdsjD7bYHt4vuQbQGqjpsABDHBfGU1aZKQ=,iv:qeI32hJR0JkoOYnof8SvM7w5IdAwuBLJcC3miAdsBhc=,tag:oU5qFjHwym/rg3JewRzvOQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
